server:
  port: 8080
csvFile:
  path: D:\IdeaProjects\transform\src\main\resources\
  name: market_quote.csv
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.1.7:3306/eladmin

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.chenahua.transform.TransformApplication: debug

